name: AdminStuff
main: com.bukkit.Souli.AdminStuff.ASCore
version: 1.0
commands:
  afk:
    description: Toggle AFK status
    usage: /afk
  ban:
    description: Ban a player
    usage: /ban <Player> [Message]    
  compass:
    description: Show the compassdir
    usage: /compass    
  chat:
    description: Chat to some people only
    usage: /chat [Player 1 .. Player n]       
  clearinventory:
    description: Clears an inventory
    usage: /clearinventory [Player]
    aliases: ['cli']
  fillchest:
    description: Fill a chest with a specified item
    usage: /fillchest <ItemID or Name>[:SubID]      
  flash:
    description: Flash a player or strike a lightning
    usage: /flash [Player]
    aliases: ['lightning']    
  give:
    description: Give items to a specific player
    usage: /give <Player> <ItemID or Name>[:SubID]    
  glue:
    description: Glue a Player
    usage: /glue <Player>
  gluehere:
    description: Glue a Player at a specific location
    usage: /gluehere <Player>    
  home:
    description: Teleport to home
    usage: /home
  i:
    description: Give yourself items
    usage: /i <ItemID or Name>[:SubID]
  invsee:
    description: See a players inventory
    usage: /invsee <Player>
  kill:
    description: Kill a Player
    usage: /kill <Player>    
  kick:
    description: Kick a player
    usage: /kick <Player> [Message]
  kickall:
    description: Kick all players
    usage: /kickall <Player> [Message]    
  msg:
    description: Message a player
    usage: /msg <Player> <Message>
    aliases: ['m', 'message']    
  mute:
    description: Mute a player
    usage: /mute <Player>      
  r:
    description: Reply to a message
    usage: /r <Message>
  sethome:
    description: Set your home to the current location
    usage: /sethome
  setspawn:
    description: Set the worldspawn to the current location
    usage: /setspawn
  slap:
    description: Slap a player
    usage: /slap <Player>
  spawn:
    description: Teleport to worldspawn
    usage: /spawn   
  tempban:
    description: Temporary ban a player
    usage: /tempban <Player> <Time>        
  time:
    description: Set the time of your world
    usage: /time <day|night>
  unlimited:
    description: Toggle unlimited Items
    usage: /unlimited <ItemID or Name> [Player]
  weather:
    description: Set the weather of your world
    usage: /weather <sun|rain|storm>